version: '3.7'

services:
    app:
        build: .
        ports:
            - '8000:8000'
        volumes:
            - '/var/www/html'
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'adminpassword'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
